data = {'current': {'cloud': 0,
             'condition': {'code': 1000,
                           'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
                           'text': 'Sunny'},
             'dewpoint_c': 7.8,
             'dewpoint_f': 46.1,
             'diff_rad': 93.7,
             'dni': 892.95,
             'feelslike_c': 26.2,
             'feelslike_f': 79.2,
             'gti': 164.22,
             'gust_kph': 3.7,
             'gust_mph': 2.3,
             'heatindex_c': 26.3,
             'heatindex_f': 79.3,
             'humidity': 37,
             'is_day': 1,
             'last_updated': '2025-08-10 16:15',
             'last_updated_epoch': 1754838900,
             'precip_in': 0.0,
             'precip_mm': 0.0,
             'pressure_in': 30.33,
             'pressure_mb': 1027.0,
             'short_rad': 749.48,
             'temp_c': 27.2,
             'temp_f': 81.0,
             'uv': 3.6,
             'vis_km': 10.0,
             'vis_miles': 6.0,
             'wind_degree': 291,
             'wind_dir': 'WNW',
             'wind_kph': 3.6,
             'wind_mph': 2.2,
             
             'windchill_c': 27.3,
             'windchill_f': 81.1},
 'location': {'country': 'United Kingdom',
              'lat': 51.5171,
              'localtime': '2025-08-10 16:17',
              'localtime_epoch': 1754839064,
              'lon': -0.1062,
              'name': 'London',
              'region': 'City of London, Greater London',
              'tz_id': 'Europe/London'}}

print(data["location"]["localtime"])